### ISSUE TITLE
同步日志记录

### ISSUE THREAD

**Issue by kinosang** [zh-h/hacpai-sync-wordpress#5]
保留日志一方面方便查询同步信息，一方面解决 #4 二次同步评论的问题

**Comment by zh-h** [comment]
我得看看创建使用第三个表去记录数据的接口

**Comment by kinosang** [comment]
@zh-h 其实我已经做了相应的尝试，保留全部双向同步记录，但是 `preprocess_comment` Hook 里面没法获取评论ID（因为这个 Hook 的调用发生在评论被插入数据库之前）

**Comment by zh-h** [comment]
@kinosang 日志记录最好有界面显示。我使用最多的插件就是多说评论，像多说一样显示一个悬浮窗。
