### ISSUE TITLE
标签可以为空

### ISSUE THREAD

**Issue by 88250** [zh-h/hacpai-sync-wordpress#7]
同步文章的时候，标签可以为空，社区这边会自动加的。

也就是说，不用带 B3log, API 这两个默认标签，请记得处理 :grapes:

**Comment by zh-h** [comment]
我当时测试，Wordpress保存文章的时候没有标签直接给我报500，不知道怎么看异常，所以硬是强行加上标签才修复。

**Comment by 88250** [comment]
哦，那就只加一个标签 B3log 吧~

**Comment by zh-h** [comment]
睡觉

**Comment by 88250** [comment]
记得关闭这个 issue 哦~
